# Generated by Django 5.0.6 on 2024-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_is_host_and_more'),
        ('core', '0008_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='wish_users', to='core.property'),
        ),
    ]
