# Generated by Django 5.0.6 on 2024-06-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_category_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
        migrations.AddField(
            model_name='category',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
