# Generated by Django 5.0.6 on 2024-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_photos_property_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
