# Generated by Django 5.0.6 on 2024-06-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
    ]
