# Generated by Django 5.0.6 on 2024-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
