# Generated by Django 5.0.6 on 2024-06-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_property_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]
